version: "3.9"

services:
  backend:
    build: ./backend
    env_file: ./.env
    ports:
      - "8000:8000"
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/code
    depends_on:
      - db

  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file: ./.env

  pgadmin:
    image: dpage/pgadmin4:latest
    depends_on:
      - db
    ports:
      - "8080:80"
    env_file: ./.env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    restart: always
    command: yarn dev
    env_file:
      - .env
    volumes:
      - ./frontend/src:/frontend/src
      - ./frontend/public:/frontend/public
    ports:
      - 4000:4000
    depends_on:
      - backend

volumes:
  postgres_data:
