name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  flake8-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Flake8
        run: pip install flake8 flake8-quotes

      - name: Run Flake8
        run: flake8 ./
  backend-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Build and run the Docker Compose stack
        run: docker-compose up -d

      - name: Run Django Tests
        run: docker-compose run backend python manage.py test
